<?php

namespace Database\Factories;

use App\Models\Post;
use App\Models\User;
use App\Models\Category;
use App\Models\SubCategory;

use Illuminate\Database\Eloquent\Factories\Factory;

class PostFactory extends Factory
{
    protected $model = Post::class;

    public function definition()
    {
        $faker = \Faker\Factory::create('en_US'); // Set the locale to English

        $images = [
           "t-shirt-5.jpg",
            "t-shirt-6.jpg",
            "t-shirt-7.jpg",
            "t-shirt-8.jpg",
            "t-shirt-9.jpg",
            "t-shirt-10.jpg",
            "t-shirt-11.jpg",
            "t-shirt-12.jpg",
            "t-shirt-13.jpg",
            "t-shirt-14.jpg" ,
            "white-1.jpg",
            "white-2.jpg",
            "white-3.jpg",
            "white-4.jpg",
            "white-5.jpg",
            "white-6.jpg",
            "white-7.jpg",
            "white-8.jpg",
            "beige-2.jpg",
            "beige-3.jpg",
            "black-1.jpg",
            "black-2.jpg",
            "black-3.jpg",
            "black-4.jpg",
            "black-5.jpg",
            "blue-4.jpg",
            "blue-5.jpg",
            "blue-6.jpg",
            "blue-7.jpg",
            "blue-8.jpg",
            "brown.jpg",
            "brown-2.jpg",
            "brown-3.jpg",
            "brown-4.jpg",
            "brown-5.jpg",
            "men-hoodie-5.jpg",
            "men-hoodie-6.jpg",
            "men-hoodie-7.jpg",
            "men-hoodie-8.jpg",
            "orange-1.jpg",
            "paddle-boards-1.jpg",

        ];
        $randomImage = $images[array_rand($images)];

        $user = User::inRandomOrder()->first();
        $category = Category::inRandomOrder()->first();
        $subCategory = SubCategory::where('category_id', $category->id)->inRandomOrder()->first();


        return [
            'title' => $faker->sentence,
            'content' => $faker->paragraph,
            'image' => $randomImage,
            'status' => 1,
            'user_id' => $user ? $user->id : null,
            'category_id' => $category ? $category->id : null,
            'sub_category_id' => $subCategory ? $subCategory->id : null,
        ];
    }


}






// "t-shirt-15.jpg"
// "t-shirt-16.jpg"
// "white-1.jpg"
// "white-2.jpg"
// "white-3.jpg"
// "white-4.jpg"
// "white-5.jpg"
// "white-6.jpg"
// "white-7.jpg"
// "white-8.jpg"
// "white-9.jpg"
// "white-10.jpg"
// "white-11.jpg"
// "white-12.jpg"
// "white-13.jpg"
// "white-14.jpg"
// "white-15.jpg"
// "white-16.jpg"
// "white-17.jpg"
// "white-18.jpg"
// "white-19.jpg"
// "white-20.jpg"
// "white-21.jpg"
// "white-22.jpg"
// "beige.jpg"
// "beige-2.jpg"
// "beige-3.jpg"
// "black-1.jpg"
// "black-2.jpg"
// "black-3.jpg"
// "black-4.jpg"
// "black-5.jpg"
// "black-6.jpg"
// "black-7.jpg"
// "black-8.jpg"
// "black-9.jpg"
// "black-10.jpg"
// "black-11.jpg"
// "black-12.jpg"
// "black-13.jpg"
// "black-14.jpg"
// "black-15.jpg"
// "black-16.jpg"
// "black-17.jpg"
// "black-18.jpg"
// "black-19.jpg"
// "black-20.jpg"
// "black-21.jpg"
// "black-22.jpg"
// "black-23.jpg"
// "black-24.jpg"
// "black-25.jpg"
// "black-26.jpg"
// "black-27.jpg"
// "black-28.jpg"
// "black-29.jpg"
// "black-30.jpg"
// "black-31.jpg"
// "black-32.jpg"
// "blue.jpg"
// "blue-2.jpg"
// "blue-3.jpg"
// "blue-4.jpg"
// "blue-5.jpg"
// "blue-6.jpg"
// "blue-7.jpg"
// "blue-8.jpg"
// "brown.jpg"
// "brown-2.jpg"
// "brown-3.jpg"
// "brown-4.jpg"
// "brown-5.jpg"
// "brown-6.jpg"
// "brown-7.jpg"
// "brown-8.jpg"
// "brown-9.jpg"
// "brown-10.jpg"
// "brown-11.jpg"
// "brown-12.jpg"
// "brown-13.jpg"
// "brown-14.jpg"
// "brown-15.jpg"
// "brown-16.jpg"
// "brown-17.jpg"
// "brown-18.jpg"
// "brown-19.jpg"
// "brown-handbag-1.jpg"
// "brown-handbag-2.jpg"
// "bubble-gum-light-green.jpg"
// "bubble-gum-yellow.jpg"
// "dark-blue.jpg"
// "dark-blue-2.jpg"
// "decor-1.jpg"
// "decor-2.jpg"
// "decor-3.jpg"
// "decor-4.jpg"
// "decor-5.jpg"
// "decor-6.jpg"
// "decor-7.jpg"
// "decor-8.jpg"
// "decor-9.jpg"
// "decor-10.jpg"
// "decor-11.jpg"
// "decor-12.jpg"
// "decor-13.jpg"
// "decor-14.jpg"
// "decor-15.jpg"
// "decor-16.jpg"
// "decor-17.jpg"
// "decor-18.jpg"
// "decor-19.jpg"
// "dog-1.jpg"
// "dog-2.jpg"
// "dog-3.jpg"
// "dog-4.jpg"
// "dog-5.jpg"
// "dog-6.jpg"
// "dog-7.jpg"
// "dog-8.jpg"
// "dog-9.jpg"
// "dog-10.jpg"
// "dog-11.jpg"
// "dog-12.jpg"
// "dog-13.jpg"
// "furniture-1.jpg"
// "furniture-2.jpg"
// "furniture-3.jpg"
// "furniture-4.jpg"
// "furniture-5.jpg"
// "furniture-6.jpg"
// "furniture-7.jpg"
// "furniture-8.jpg"
// "furniture-9.jpg"
// "furniture-10.jpg"
// "furniture-11.jpg"
// "furniture-12.jpg"
// "furniture-13.jpg"
// "giftcard-1.jpg"
// "giftcard-2.jpg"
// "giftcard-3.jpg"
// "giftcard-4.jpg"
// "giftcard-5.jpg"
// "giftcard-6.jpg"
// "giftcard-7.jpg"
// "giftcard-8.jpg"
// "glasses-1.jpg"
// "glasses-2.jpg"
// "glasses-3.jpg"
// "glasses-4.jpg"
// "glasses-5.jpg"
// "glasses-6.jpg"
// "glasses-7.jpg"
// "glasses-8.jpg"
// "glasses-9.jpg"
// "glasses-10.jpg"
// "glasses-11.jpg"
// "glasses-12.jpg"
// "glasses-13.jpg"
// "glasses-14.jpg"
// "glasses-15.jpg"
// "glasses-16.jpg"
// "glasses-17.jpg"
// "glasses-18.jpg"
// "green.jpg"
// "green-2.jpg"
// "green-3.jpg"
// "green-4.jpg"
// "green-5.jpg"
// "green-6.jpg"
// "green-7.jpg"
// "green-handbag-1.jpg"
// "green-handbag-2.jpg"
// "grey.jpg"
// "grey-2.jpg"
// "grey-3.jpg"
// "grey-4.jpg"
// "grey-5.jpg"
// "hat.jpg"
// "hat-2.jpg"
// "headphone-1.png"
// "headphone-2.png"
// "headphone-3.png"
// "headphone-4.png"
// "headphone-5.png"
// "headphone-6.png"
// "headphone-7.png"
// "headphone-8.png"
// "headphone-9.png"
// "headphone-10.png"
// "headphone-11.png"
// "headphone-12.png"
// "headphone-13.png"
// "headphone-14.png"
// "headphone-15.png"
// "headphone-16.png"
// "headphone-17.png"
// "headphone-18.png"
// "headphone-19.png"
// "img-feature-1.png"
// "img-feature-2.png"
// "img-feature-3.png"
// "jewerly-1.jpg"
// "jewerly-2.jpg"
// "jewerly-3.jpg"
// "jewerly-4.jpg"
// "jewerly-5.jpg"
// "jewerly-6.jpg"
// "jewerly-7.jpg"
// "jewerly-8.jpg"
// "jewerly-9.jpg"
// "jewerly-10.jpg"
// "kid-1.jpg"
// "kid-2.jpg"
// "kid-3.jpg"
// "kid-4.jpg"
// "kid-5.jpg"
// "kid-6.jpg"
// "kid-7.jpg"
// "kid-8.jpg"
// "kid-9.jpg"
// "kid-10.jpg"
// "kid-11.jpg"
// "kid-12.jpg"
// "kid-13.jpg"
// "kid-14.jpg"
// "kid-15.jpg"
// "kitchen-wear-1.jpg"
// "kitchen-wear-2.jpg"
// "kitchen-wear-3.jpg"
// "kitchen-wear-4.jpg"
// "kitchen-wear-5.jpg"
// "kitchen-wear-6.jpg"
// "kitchen-wear-7.jpg"
// "kitchen-wear-8.jpg"
// "kitchen-wear-9.jpg"
// "kitchen-wear-10.jpg"
// "kitchen-wear-11.jpg"
// "kitchen-wear-12.jpg"
// "kitchen-wear-13.jpg"
// "lamp-black.jpg"
// "lamp-dark-green.jpg"
// "lb-men-1.jpg"
// "lb-men-2.jpg"
// "light-blue.jpg"
// "light-blue-2.jpg"
// "light-blue-3.jpg"
// "light-blue-4.jpg"
// "light-blue-5.jpg"
// "light-green-1.jpg"
// "light-green-2.jpg"
// "light-green-4.jpg"
// "light-green-5.jpg"
// "light-green-6.jpg"
// "light-grey.jpg"
// "light-pink.jpg"
// "men-hoodie.jpg"
// "men-hoodie-2.jpg"
// "men-hoodie-3.jpg"
// "men-hoodie-4.jpg"
// "men-hoodie-5.jpg"
// "men-hoodie-6.jpg"
// "men-hoodie-7.jpg"
// "men-hoodie-8.jpg"
// "orange-1.jpg"
// "paddle-boards-1.jpg"
// "paddle-boards-1-small.jpg"
// "paddle-boards-2.jpg"
// "paddle-boards-2-small.jpg"
// "paddle-boards-3.jpg"
// "paddle-boards-3-small.jpg"
// "paddle-boards-4.jpg"
// "paddle-boards-4-small.jpg"
// "paddle-boards-5.jpg"
// "paddle-boards-6.jpg"
// "paddle-boards-7.jpg"
// "paddle-boards-8.jpg"
// "paddle-boards-9.jpg"
// "paddle-boards-10.jpg"
// "paddle-boards-11.jpg"
// "paddle-boards-12.jpg"
// "phonecase-1.jpg"
// "phonecase-2.jpg"
// "phonecase-3.jpg"
// "phonecase-4.jpg"
// "phonecase-5.jpg"
// "phonecase-6.jpg"
// "phonecase-7.jpg"
// "phonecase-8.jpg"
// "phonecase-9.jpg"
// "phonecase-10.jpg"
// "phonecase-11.jpg"
// "phonecase-12.jpg"
// "pink-1.jpg"
// "pink-2.jpg"
// "pink-3.jpg"
// "pink-4.jpg"
// "pink-5.jpg"
// "pink-handbag-1.jpg"
// "pink-handbag-2.jpg"
// "playing-card-1.jpg"
// "playing-card-2.jpg"
// "pod-store-1.jpg"
// "pod-store-3.jpg"
// "pod-store-4.jpg"
// "pod-store-5.jpg"
// "pod-store-6.jpg"
// "pod-store-7.jpg"
// "pod-store-8.jpg"
// "pod-store-9.jpg"
// "pod-store-10.jpg"
// "pod-store-11.jpg"
// "pod-store-12.jpg"
// "pod-store-13.jpg"
// "pod-store-14.jpg"
// "pod-store-15.jpg"
// "pod-store-16.jpg"
// "pod-store-17.png"
// "pod-store-18.jpg"
// "pod-store-19.jpg"
// "pod-store-20.jpg"
// "pod-store-21.jpg"
// "pod-store-22.jpg"
// "pod-store-23.jpg"
// "pod-store-24.jpg"
// "pod-store-25.jpg"
// "purple.jpg"
// "purple-2.jpg"
// "red.jpg"
// "setup-gear-1.jpg"
// "setup-gear-2.jpg"
// "setup-gear-3.jpg"
// "setup-gear-4.jpg"
// "setup-gear-5.jpg"
// "setup-gear-6.jpg"
// "setup-gear-7.jpg"
// "setup-gear-8.jpg"
// "setup-gear-9.jpg"
// "setup-gear-10.jpg"
// "setup-gear-11.jpg"
// "setup-gear-12.jpg"
// "setup-gear-13.png"
// "setup-gear-14.jpg"
// "setup-gear-15.jpg"
// "setup-gear-16.jpg"
// "setup-gear-17.jpg"
// "setup-gear-18.jpg"
// "setup-gear-19.jpg"
// "skateboard-grind-rail-light-green.jpg"
// "skateboard-grind-rail-white.jpg"
// "skateboards-tool-black.jpg"
// "skateboards-tool-pink.jpg"
// "skateboards-tool-red.jpg"
// "skincare-1.jpg"
// "skincare-2.jpg"
// "skincare-3.jpg"
// "skincare-4.jpg"
// "skincare-5.jpg"
// "skincare-6.jpg"
// "skincare-7.jpg"
// "skincare-8.jpg"
// "skincare-9.jpg"
// "skincare-10.jpg"
// "skincare-11.jpg"
// "skincare-12.jpg"
// "skincare-13.jpg"
// "skincare-14.jpg"
// "skincare-15.jpg"
// "skincare-16.jpg"
// "sneaker-1.png"
// "sneaker-2.jpg"
// "sneaker-3.png"
// "sneaker-4.png"
// "sneaker-5.png"
// "sneaker-6.png"
// "sneaker-7.jpg"
// "sneaker-8.jpg"
// "sneaker-9.png"
// "sneaker-10.png"
// "sock1.jpg"
// "sock2.jpg"
// "sock3.jpg"
// "sock4.jpg"
// "sock5.jpg"
// "sock6.jpg"
// "sock7.jpg"
// "sock8.jpg"
// "sock9.jpg"
// "sock10.jpg"
// "sock11.jpg"
// "sock12.jpg"
// "sock13.jpg"
// "sock14.jpg"
// "sock15.jpg"
// "sock16.jpg"
// "sports-clothing.jpg"
// "sports-clothing-2.jpg"
// "sports-clothing-3.jpg"
// "sports-clothing-4.jpg"
// "sports-clothing-5.jpg"
// "sports-clothing-6.jpg"
// "sports-clothing-7.jpg"
// "sports-clothing-8.jpg"
// "stakeboard-black.jpg"
// "stakeboard-black2.jpg"
// "stakeboard-black3.jpg"
// "stakeboard-blackwhite.jpg"
// "stakeboard-blackwhite2.jpg"
// "stakeboard-blueblack.jpg"
// "stakeboard-bluewhite.jpg"
// "stakeboard-greenblack.jpg"
// "stakeboard-lightgreen.jpg"
// "stakeboard-orange.jpg"
// "stakeboard-orange2.jpg"
// "stakeboard-purple.jpg"
// "stakeboard-purple2.jpg"
// "stakeboard-redblack.jpg"
// "stakeboard-whitestriped.jpg"
// "stakeboard-yellowblack.jpg"
// "stroller-baby-beige.jpg"
// "stroller-baby-black.jpg"
// "stroller-baby-black2.jpg"
// "stroller-baby-black3.jpg"
// "stroller-baby-black4.jpg"
// "stroller-baby-black5.jpg"
// "stroller-baby-brown.jpg"
// "stroller-baby-darkblue.jpg"
// "stroller-baby-darkgreen.jpg"
// "stroller-baby-grey.jpg"
// "stroller-baby-pink.jpg"
// "stroller-baby-yellow.jpg"
// "sunglasses-black.jpg"
// "sunglasses-blue.jpg"
// "sunglasses-red.jpg"
// "taupe-1.jpg"
// "t-shirt.jpg"
// "t-shirt-2.jpg"
// "t-shirt-3.jpg"
// "t-shirt-4.jpg"
// "t-shirt-5.jpg"
// "t-shirt-6.jpg"
// "t-shirt-7.jpg"
// "t-shirt-8.jpg"
// "t-shirt-9.jpg"
// "t-shirt-10.jpg"
// "t-shirt-11.jpg"
// "t-shirt-12.jpg"
// "t-shirt-13.jpg"
// "t-shirt-14.jpg" 
